### ISSUE TITLE
Missing readme / notes for contributors

### ISSUE THREAD

**Issue by kaushal-py** [minitorch/minitorch.github.io#2]
This project seems very interesting to me, and would love to contribute to it. Is it possible to have a readme and some notes for contributors like me so that we could help to develop it?

**Comment by srush** [comment]
Sure. Pitch me a project, and I will add you to the hidden master repo.

**Comment by FZSS** [comment]
I found a few trivial typos in module 2, would like to know how can I make a pull request for the corrections.
