### ISSUE TITLE
Open sourcing course syllabus 

### ISSUE THREAD

**Issue by TuanNguyen27** [minitorch/minitorch.github.io#3]
Thanks for creating a great learning resource! I found https://canvas.cornell.edu/courses/20583/assignments/syllabus but the individual units require a canvas account to access. I am wondering if the entire course will be publicly available at some point. :)

**Comment by srush** [comment]
Curious what aspects you are interested in? Almost all the course material is available on the web. Canvas mostly just has slides and answers.

**Comment by TuanNguyen27** [comment]
Ah indeed the project documentation contains most of the materials. Thanks for answering!
